import = [
  "~/.config/alacritty/current-theme.toml",
]

live_config_reload = true

[window]
decorations = "Transparent"  # macOS
padding = { x = 15, y = 40 }
dynamic_padding = true
opacity = 0.7
blur = true  # macOS

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 18

[cursor]
style = { shape = "block", blinking = "always" }
blink_interval = 500


