import = [
  "~/.config/alacritty/current-theme.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# decorations = "Transparent"  # macOS
decorations = "Full"  # macOS
decorations_theme_variant = "Dark"
title = "¯\\_(ツ)_/¯"

padding.x = 15
padding.y = 15

dynamic_padding = true

resize_increments = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[cursor]
style.shape = "block"
style.blinking = "always"
blink_interval = 500

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
